---
title: "AI Hackathon"
subtitle: "2024-11-19 – Cohort 9"
format:
  revealjs:
    theme: simple
    transition: slide
    slide-number: true
    chalkboard: true
editor:
  render-on-save: true
---

```{r include=FALSE}
slack_channel <- "#hackathon-09"
```

# Welcome

- Before we begin, please join <code>`r slack_channel`</code> in Slack!
- Also, please clone this repo:\
  [https://github.com/jcheng5/llm-quickstart](https://github.com/jcheng5/llm-quickstart)

## Who's Here {.smaller}

::: {.columns}
::: {.column width="50%"}
**Participants:**

- Barret Schloerke
- Brian Tackett
- Bruno Trimouille
- David Aja
- Garrick Aden-Buie
- Ibi Togun
- Ingrid Rodriguez
- Jason Milnes
- Mel Gregory
:::
::: {.column width="50%"}
**Organizers:**

- Andrew Holz
- Joe Cheng
- Winston Chang
:::
:::

## Your Turn

- What do you do at Posit?
- How have you used LLMs/AI tools up until now?
- What is your skepticism/enthusiasm score (1 to 5)?

## The Plan

```{css}
section#the-plan li[data-fragment-index="3"] {
  border-top: 1px solid #ccc;
  margin-top: 1em;
  padding-top: 1em;
}
```

::: {.incremental}
- **Now:** Quick Start course on LLMs. You will leave having used a Chat API.
- **Next 48 hours:** Hack on stuff! Minimum four hours of effort. "Rules" on the next slide.
- **Thursday:** Show & tell, share lessons learned, reflections.
- **Post-hackathon:**
  - Keep hacking! (optional)
  - Think about how AI might apply to your team
  - Be a resource for others around you
:::

## Hack On Stuff

- **Does NOT have to be relevant to your day job, or Posit, or data science.**\
  This exercise is about learning and engagement, not ROI.
- **Does NOT have to be a finished product/demo/app/API.**\
  Showing some things you did in a notebook is fine as long as YOU found it interesting.
- **Does NOT have to use Posit products.**\
  You may use any framework, any language,any service that you have access to.

## Hack On Stuff

- **Does NOT have to be an original idea.**\
  You can build on existing projects, improve on existing demos, etc.
- **Does NOT even have to be coding.**\
  Do a deep dive into an AI service or piece of software. Make an interesting project on ChatGPT Playground > Assistants, or assemble a useful NotebookLM and see what its limits are.
- **Does NOT have to be a success.**\
  Negative results (“I thought LLMs could do this but turns out they can’t”) are useful results as well. But please be prepared to talk about what you tried.

## Not a contest

- This is not a competition. There are no prizes, no judging.
- Everyone is coming from different backgrounds and has different levels of experience with AI, with coding, etc.
- The goal is to learn, to have fun, and to engage with the technology---and share what you learned with others (and not just within this cohort).

## Let It Rip

* All that said... also feel free to throw down, and make something super cool!

::: {.incremental}

* Four hours is the minimum, not the maximum---if you're having fun, keep going!

:::

## A Caveat From IT

No _proprietary_ code or data is allowed to be sent to any LLM service, with the below exceptions.

- Google NotebookLM is allowed.
- AWS Bedrock is allowed, and it has Anthropic models. We can help you set this up.
- Running any local model is allowed, we can help you with this as well.
- Sending open source code to any service is allowed.

# Next: [Quick Start](quickstart.qmd)